### ISSUE TITLE
Token still valid with runtime error

### ISSUE THREAD

**Issue by samuelbastos** [fabiofalci/sconsify#105]
Hello,

Recently I tried modifying the expireTime of the token string from 3600 to a random number, which I do not remember at the moment. It worked for a while, but now when I try to login I get the "Token still valid" message with a runtime error right after it. 

`goroutine 69 [running]:
github.com/fabiofalci/sconsify/spotify.(*portAudio).player(0xc42019a008)
	/go/src/github.com/fabiofalci/sconsify/spotify/portaudio.go:33 +0x28b
created by github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:166 +0x66
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 7 [running]:
github.com/fabiofalci/sconsify/vendor/github.com/fabiofalci/go-libspotify/spotify.newPlaylistContainer.func4(0x7fd15800be10, 0xc420038d30, 0xc420038d20, 0x8d3560)
	/go/src/github.com/fabiofalci/sconsify/vendor/github.com/fabiofalci/go-libspotify/spotify/libspotify.go:1352 +0xee
github.com/fabiofalci/sconsify/vendor/github.com/fabiofalci/go-libspotify/spotify.newPlaylistContainer(0xc4201d4000, 0x0, 0x0, 0x0)
	/go/src/github.com/fabiofalci/sconsify/vendor/github.com/fabiofalci/go-libspotify/spotify/libspotify.go:1352 +0x1d2
github.com/fabiofalci/sconsify/vendor/github.com/fabiofalci/go-libspotify/spotify.(*Session).Playlists(0xc4201d4000, 0x1, 0x1, 0x82)
	/go/src/github.com/fabiofalci/sconsify/vendor/github.com/fabiofalci/go-libspotify/spotify/libspotify.go:535 +0x2b
github.com/fabiofalci/sconsify/spotify.(*Spotify).initLibspotifyPlaylist(0xc4201b4000, 0xc42007fde0, 0x200000003, 0xc420001980)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify_playlists.go:94 +0x93
github.com/fabiofalci/sconsify/spotify.(*Spotify).initPlaylist(0xc4201b4000, 0x8d3720, 0xc42019a008)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify_playlists.go:23 +0x863
github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation(0xc4201b4000, 0xc4200383c0, 0xc42019a008, 0x0, 0x0)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:169 +0x90
github.com/fabiofalci/sconsify/spotify.(*Spotify).checkIfLoggedIn(0xc4201b4000, 0xc4200383c0, 0xc42019a008, 0xc42002a970, 0xb)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:122 +0xb4
github.com/fabiofalci/sconsify/spotify.initialiseSpotify(0xc4200383c0, 0xc42002a910, 0x8, 0xc42002a970, 0xb, 0x10, 0xc4201b2000, 0xd6c6d8, 0x0, 0x0)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:62 +0x214
github.com/fabiofalci/sconsify/spotify.Initialise(0xc4200383c0, 0xc42002a910, 0x8, 0xc42002a970, 0xb, 0x10, 0xc4201b2000, 0xd6c6d8)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:41 +0x87
created by main.main
	/go/src/github.com/fabiofalci/sconsify/sconsify.go:108 +0x7df
`

I know it's mainly my fault your app is not working for me anymore, but if you can find a easy solution I would really appreciate it, you've done a really good job with Sconsify, I love it!

**Comment by samuelbastos** [comment]
Actually I cannot find it, tried locating it and nothing. I also tried using the flag -issue-web-api-token to see if it could overwrite the old token but apparently it can't
