### ISSUE TITLE
panic: spotify: track artist index out of range

### ISSUE THREAD

**Issue by mrbohnke** [fabiofalci/sconsify#26]
Did something weird happen over the weekend?

```
Sconsify - your awesome Spotify music service in a text-mode interface.
Provided username: myusername
Password: *******
2016-01-25 11:45:19.250 sconsify[21250:2329953] 11:45:19.250 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

**panic: spotify: track artist index out of range**

goroutine 20 [running]:
github.com/op/go-libspotify/spotify.(*Track).Artist(0xc82032ca80, 0x0, 0x4005fac)
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:1901 +0xd3
github.com/fabiofalci/sconsify/sconsify.ToSconsifyTrack(0xc82032ca80, 0x0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/sconsify/track.go:32 +0x39
github.com/fabiofalci/sconsify/spotify.(*Spotify).initTrack(0xc82003fe78, 0xc8203277e0, 0xc8203277e0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify_playlists.go:63 +0x97
github.com/fabiofalci/sconsify/spotify.(*Spotify).initPlaylist(0xc82003fe78, 0x0, 0x0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify_playlists.go:42 +0x352
github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation(0xc82003fe78, 0xc82002e008, 0x0, 0x0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:127 +0x75
github.com/fabiofalci/sconsify/spotify.(*Spotify).checkIfLoggedIn(0xc82003fe78, 0xc82002e008, 0x0, 0x0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:96 +0x117
github.com/fabiofalci/sconsify/spotify.initialiseSpotify(0xc8200983aa, 0x8, 0xc820070d80, 0xc, 0x10, 0xc82006c960, 0xc820070ba0, 0x0, 0x0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:45 +0x241
github.com/fabiofalci/sconsify/spotify.Initialise(0xc8200983aa, 0x8, 0xc820070d80, 0xc, 0x10, 0xc82006c960, 0xc820070ba0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:25 +0x7e
created by main.main
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/sconsify.go:56 +0xb12

goroutine 1 [select]:
github.com/fabiofalci/sconsify/sconsify.StartMainLoop(0xc82006c960, 0x5804528, 0x4398480, 0x5804500, 0x0, 0x0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/sconsify/mainloop.go:4 +0x6ee
main.main()
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/sconsify.go:60 +0xd4a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1

goroutine 19 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 4 [select, locked to thread]:
github.com/op/go-libspotify/spotify.(*Session).processEvents(0xc8200d6000)
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:886 +0x372
github.com/op/go-libspotify/spotify.NewSession.func1(0xc8200d6000, 0xc8200186c0)
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:243 +0x1a0
created by github.com/op/go-libspotify/spotify.NewSession
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:244 +0x6e3

goroutine 5 [select]:
github.com/op/go-libspotify/spotify.(*Session).processBackground(0xc8200d6000)
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:900 +0x2c1
created by github.com/op/go-libspotify/spotify.NewSession
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:250 +0x788

goroutine 34 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1

goroutine 35 [chan send]:
github.com/fabiofalci/sconsify/spotify.(*Spotify).waitForSuccessfulConnectionStateUpdates.func1(0xc820110060)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:103 +0x4f
created by github.com/fabiofalci/sconsify/spotify.(*Spotify).waitForSuccessfulConnectionStateUpdates
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:104 +0x5f

goroutine 7 [chan receive]:
github.com/fabiofalci/sconsify/spotify.(*portAudio).player(0xc82002e008)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/portaudio.go:50 +0x252
created by github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:124 +0x4a
```

**Comment by fabiofalci** [comment]
That's odd.
Nothing has changed on sconsify.

The problem is this line which gets the first artist from the track:

`artist := track.Artist(0)`

I was hoping every track to have at least one artist, it looks like you found a track without artist.

Have you changed your playlists over the weekend?
Or maybe the `Discover Weekly` from spotify included a new track there without the artist.

**Comment by mrbohnke** [comment]
Certainly odd. I use to make some new playlists every week. I'm looking through the new ones and can't find a track without artist:
https://open.spotify.com/user/mrbohnke/playlist/75cD0pbyhzBQEbXd3MpoBJ
https://open.spotify.com/user/mrbohnke/playlist/23GE9H10AVT0Bgqay0hfeo
https://open.spotify.com/user/mrbohnke/playlist/2YNtfQHWIBMhTXgDZc0Eg0
https://open.spotify.com/user/spotifydiscover/playlist/3WFwgXm1isQHIth5XYoDPX
I removed these ones (as well as the Discover Weekly one), though, but it didn't get to work.

**Comment by mrbohnke** [comment]
I've been thinking about this. If the funky track was in an old playlist made by someone else… the chances to get to know which one it is are really small, since I have a collection of hundreds of playlist…
The trick here, if possible, would be to make Sconsify to tell me which track does he have a problem with… what do you think?
Thank you for your time,
Cheers!

**Comment by fabiofalci** [comment]
Haha.

Ok good.
I'll 2 things for next release. First will handle null artist so next time at least we don't throw an error to the user and then I'll improve logging and output all loaded tracks when debug flag is on so we can at least now the problematic track.

Thank you!
