### ISSUE TITLE
crash on new session

### ISSUE THREAD

**Issue by fritzy** [fabiofalci/sconsify#41]
```
Password: [password stars here]
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 3 [running, locked to thread]:
panic(0x4527b8, 0x109240e0)
	/usr/local/go/src/runtime/panic.go:481 +0x330
github.com/fabiofalci/sconsify/vendor/github.com/op/go-libspotify/spotify.NewSession.func1(0x109009c0, 0x109125c0)
	/home/pi/local/go/src/github.com/fabiofalci/sconsify/vendor/github.com/op/go-libspotify/spotify/libspotify.go:238 +0x134
created by github.com/fabiofalci/sconsify/vendor/github.com/op/go-libspotify/spotify.NewSession
	/home/pi/local/go/src/github.com/fabiofalci/sconsify/vendor/github.com/op/go-libspotify/spotify/libspotify.go:244 +0x62c
```

**Comment by fabiofalci** [comment]
Have you compiled by yourself?
What go version are you using?

You need to use 1.5 as 1.6 doesn't work yet due to a change in some cgo pointer rules.

**Comment by fabiofalci** [comment]
Please try with go 1.5. Closing.
