### ISSUE TITLE
Having a folder in your playlists causes a crash after sign in

### ISSUE THREAD

**Issue by mikenew12** [fabiofalci/sconsify#5]
If one of your playlists is a folder (which you can create in the desktop client by right-clicking), sconsify will crash after signing in. Or rather it may be be libspotify that's causing the crash. Removing the folder resolves the issue.

```
panic: spotify: index does not hold a playlist entry

goroutine 6 [running]:
github.com/op/go-libspotify/spotify.(*PlaylistContainer).Playlist(0xc20802d380, 0x11, 0x8)
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:1412 +0xd6
github.com/fabiofalci/sconsify/spotify.(*Spotify).initPlaylist(0xc20802c9c0, 0x0, 0x0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify_playlists.go:19 +0x153
github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation(0xc20802c9c0, 0xc208038098, 0x0, 0x0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:126 +0x6f
github.com/fabiofalci/sconsify/spotify.(*Spotify).checkIfLoggedIn(0xc20802c9c0, 0xc208038098, 0x0, 0x0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:95 +0x12c
github.com/fabiofalci/sconsify/spotify.initialiseSpotify(0xc20800a940, 0x5, 0xc20800a9a0, 0x8, 0x8, 0xc20802c960, 0xc20800a8b0, 0x0, 0x0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:44 +0x26e
github.com/fabiofalci/sconsify/spotify.Initialise(0xc20800a940, 0x5, 0xc20800a9a0, 0x8, 0x8, 0xc20802c960, 0xc20800a8b0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:24 +0x81
created by main.main
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/sconsify.go:55 +0x76d

goroutine 1 [select]:
github.com/fabiofalci/sconsify/sconsify.StartMainLoop(0xc20802c960, 0x4694d20, 0x4331300, 0x0, 0x0, 0x0)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/sconsify/mainloop.go:4 +0x63a
main.main()
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/sconsify.go:59 +0x7c1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [select, locked to thread]:
github.com/op/go-libspotify/spotify.(*Session).processEvents(0xc20808c000)
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:886 +0x340
github.com/op/go-libspotify/spotify.func·001()
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:243 +0x141
created by github.com/op/go-libspotify/spotify.NewSession
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:244 +0x819

goroutine 9 [select]:
github.com/op/go-libspotify/spotify.(*Session).processBackground(0xc20808c000)
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:900 +0x2ad
created by github.com/op/go-libspotify/spotify.NewSession
	/Users/fabio/go/src/github.com/op/go-libspotify/spotify/libspotify.go:250 +0x8c8

goroutine 18 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 10 [sleep]:
github.com/fabiofalci/sconsify/spotify.func·001()
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:101 +0x36
created by github.com/fabiofalci/sconsify/spotify.(*Spotify).waitForSuccessfulConnectionStateUpdates
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:103 +0xc1

goroutine 11 [chan receive]:
github.com/fabiofalci/sconsify/spotify.(*portAudio).player(0xc208038098)
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/portaudio.go:50 +0x25d
created by github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation
	/Users/fabio/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:123 +0x49
```

**Comment by fabiofalci** [comment]
Thanks @mikenew12, that's exactly what is happening #3 

go-libspotify, which is a wrapper for libspotify, panics when a playlist is different than a normal playlist. I'll raise this issue there.

**Comment by mikenew12** [comment]
@fabiofalci Ah gotcha. I didn't realize at first glance it was the same issue.

**Comment by fabiofalci** [comment]
No worries mate, Thanks for reporting.

**Comment by oschrenk** [comment]
Same issues. Guess I have to wait for the issue to fixed in `go-libspotify`.

**Comment by fabiofalci** [comment]
Hi @mikenew12 @oschrenk 

There is a fix for PlaylistFolder. Please can you help test this issue?
https://github.com/fabiofalci/sconsify/releases/tag/v0.1.1-rc1

Thanks

**Comment by mikenew12** [comment]
@fabiofalci Works great! Folders aren't currently shown in sconsify, but they don't seem to cause a crash anymore. I'm testing on 10.10.3. I'll use it while I work today so I should be able to give it a pretty thorough test.

**Comment by fabiofalci** [comment]
Awesome, thank you for testing.

Yeah, as a quick fix we're ignoring the Folder meaning so the inner playlists won't be grouped together but only handled just like a normal one.

Next version we can try to sort this out as a real Folder.
