### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by irishmac473** [fabiofalci/sconsify#74]
Installed on Manjaro i3. I enter my uname and passw. It asks for web api token. I enter it and get this.
`panic: runtime error: index out of range

goroutine 19 [running]:
panic(0x805360, 0xc42000c110)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/fabiofalci/sconsify/webapi.Auth(0x8b5720, 0x20, 0x8b59e0, 0x35, 0x180001, 0x0)
	/go/src/github.com/fabiofalci/sconsify/webapi/web_auth.go:51 +0x887
github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation(0xc420136770, 0xc420124280, 0xc42012a048, 0x0, 0x0)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:146 +0x12d
github.com/fabiofalci/sconsify/spotify.(*Spotify).checkIfLoggedIn(0xc420136770, 0xc420124280, 0xc42012a048, 0xc420128368, 0x8)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:120 +0x5a
github.com/fabiofalci/sconsify/spotify.initialiseSpotify(0xc420124280, 0xc420128348, 0x7, 0xc420128368, 0x8, 0x8, 0xc420130100, 0x0, 0x0)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:60 +0x22a
github.com/fabiofalci/sconsify/spotify.Initialise(0xc420124280, 0xc420128348, 0x7, 0xc420128368, 0x8, 0x8, 0xc420130100)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:39 +0x7a
created by main.main
	/go/src/github.com/fabiofalci/sconsify/sconsify.go:85 +0xaad
`

**Comment by phoracek** [comment]
I have the same problem. Fedora 25 with i3.

**Comment by fabiofalci** [comment]
@irishmac473 @phoracek please can you check if you're copying the whole text?
The token has this format,including whitespaces:

```
access_token:BIG_TOKEN_STRING token_type:Bearer expiresIn:3600
```

**Comment by phoracek** [comment]
thanks a lot Fabio, works now, great app! :)
