### ISSUE TITLE
Cannot start sconsify

### ISSUE THREAD

**Issue by ikciwor** [fabiofalci/sconsify#79]
Hello,
I am running version
```
Version: 0.4.0
Git commit: e66d783
Build date: 2017-02-08 21:39:48 +0000 UTC
Go version: go1.7.5

```
When I use -web-api I get 
`Error: Username doesn't match with web-api authorization`
error. Turning this flag to false produces such a log:
```
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Warning: not using -web-api flag. Sconsify will load playlists using deprecated libspotify API. If not working try -web-api flag.
panic: Internal PortAudio error

goroutine 51 [running]:
panic(0x7f77c0, 0xc4201b4074)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/fabiofalci/sconsify/spotify.(*portAudio).player(0xc420134028)
	/go/src/github.com/fabiofalci/sconsify/spotify/portaudio.go:33 +0x295
created by github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:159 +0x6a
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 19 [running]:
panic(0x805360, 0xc42012e4e0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/fabiofalci/sconsify/vendor/github.com/fabiofalci/go-libspotify/spotify._cgoCheckPointer0(0xc42013f0e0, 0x0, 0x0, 0x0, 0x1)
	??:0 +0x59
github.com/fabiofalci/sconsify/vendor/github.com/fabiofalci/go-libspotify/spotify.newPlaylistContainer(0xc42016e000, 0x0, 0x0, 0x0)
	/go/src/github.com/fabiofalci/sconsify/vendor/github.com/fabiofalci/go-libspotify/spotify/libspotify.go:1352 +0x4d1
github.com/fabiofalci/sconsify/vendor/github.com/fabiofalci/go-libspotify/spotify.(*Session).Playlists(0xc42016e000, 0x1, 0x1, 0x82)
	/go/src/github.com/fabiofalci/sconsify/vendor/github.com/fabiofalci/go-libspotify/spotify/libspotify.go:535 +0x2b
github.com/fabiofalci/sconsify/spotify.(*Spotify).initLibspotifyPlaylist(0xc420140770, 0xc420037dd0, 0xc420132810, 0x0)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify_playlists.go:94 +0x103
github.com/fabiofalci/sconsify/spotify.(*Spotify).initPlaylist(0xc420140770, 0x8b3820, 0xc420134028)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify_playlists.go:23 +0xae6
github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation(0xc420140770, 0xc4201420f0, 0xc420134028, 0x0, 0x0)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:162 +0x94
github.com/fabiofalci/sconsify/spotify.(*Spotify).checkIfLoggedIn(0xc420140770, 0xc4201420f0, 0xc420134028, 0xc42012e258, 0x7)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:120 +0x5a
github.com/fabiofalci/sconsify/spotify.initialiseSpotify(0xc4201420f0, 0xc42012e230, 0x9, 0xc42012e258, 0x7, 0x8, 0xc42013a080, 0x0, 0x0)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:60 +0x22a
github.com/fabiofalci/sconsify/spotify.Initialise(0xc4201420f0, 0xc42012e230, 0x9, 0xc42012e258, 0x7, 0x8, 0xc42013a080)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:39 +0x7a
created by main.main
	/go/src/github.com/fabiofalci/sconsify/sconsify.go:85 +0xaad
```

I am using facebook login. As my username I have typed my facebook email and facebook password as password. What could go wrong and how can I fix it?

**Comment by remembertoremind** [comment]
Make sure that it really is your account name. I thought my was the same as facebook but it was not. Start Spotify on another computer and find your correct username :) Sounds kinda obvious but.. Just in case.
