### ISSUE TITLE
index of of range error when loading playlists

### ISSUE THREAD

**Issue by klarre908** [fabiofalci/sconsify#90]
```
Loaded 50 from 447 playlists
Loaded 100 from 447 playlists
Loaded 150 from 447 playlists
Loaded 200 from 447 playlists
Loaded 250 from 447 playlists
Loaded 300 from 447 playlists
panic: runtime error: index out of range

goroutine 22 [running]:
panic(0x805360, 0xc420016140)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/fabiofalci/sconsify/spotify.(*Spotify).loadPlaylistTracks(0xc42014a000, 0xc420219a00, 0xc420219db0, 0x0, 0x0)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify_playlists.go:174 +0xac6
github.com/fabiofalci/sconsify/spotify.(*Spotify).loadPlaylists(0xc42014a000, 0x12c, 0xc42010a0c0, 0xc420219db0, 0x2, 0x1e)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify_playlists.go:147 +0x136
github.com/fabiofalci/sconsify/spotify.(*Spotify).initWebApiPlaylist(0xc42014a000, 0xc420219db0, 0xc42040e840, 0x0)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify_playlists.go:75 +0xbe
github.com/fabiofalci/sconsify/spotify.(*Spotify).initPlaylist(0xc42014a000, 0x8b3820, 0xc420150000)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify_playlists.go:19 +0xc0
github.com/fabiofalci/sconsify/spotify.(*Spotify).finishInitialisation(0xc42014a000, 0xc420072a50, 0xc420150000, 0x0, 0x0)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:162 +0x94
github.com/fabiofalci/sconsify/spotify.(*Spotify).checkIfLoggedIn(0xc42014a000, 0xc420072a50, 0xc420150000, 0xc420079990, 0xc)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:120 +0x5a
github.com/fabiofalci/sconsify/spotify.initialiseSpotify(0xc420072a50, 0xc420079860, 0x6, 0xc420079990, 0xc, 0x10, 0xc42009c500, 0x0, 0x0)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:60 +0x22a
github.com/fabiofalci/sconsify/spotify.Initialise(0xc420072a50, 0xc420079860, 0x6, 0xc420079990, 0xc, 0x10, 0xc42009c500)
	/go/src/github.com/fabiofalci/sconsify/spotify/spotify.go:39 +0x7a
created by main.main
	/go/src/github.com/fabiofalci/sconsify/sconsify.go:85 +0xaad
```

**Comment by fabiofalci** [comment]
Hi @klarre908 
Can you test using this version:

https://github.com/fabiofalci/sconsify/releases/tag/next-20170531

It seems a bug when the track doesn't have at least on artist, that has been fixed on that release candidate version.

**Comment by klarre908** [comment]
It works. :)
